### PR TITLE
Add md docs for standardised docs

### PR DESCRIPTION
**Pull request by gruunday**
*I confirm that before submitting this PR, I did the following:*
  - [x] *Ran `cargo build` and confirmed that there were no warnings.*
  - [x] *Ran `cargo clippy` and confirmed that there were no warnings.*

### CODE REVIEW

**Comment by butlerx** [comment]
is this just a copy of the api blueprint?

**Comment by theycallmemac** [comment]
Looks like it is, is there any reason why it shouldn't be md @butlerx ? If not, should @gruunday can you also remove the api blueprint and add it to this PR?

**Comment by gruunday** [comment]
Yup, 
It renders to markdown readably and having the markdown file allows this documentation to be standardized in markdown so that all the Repos look the same.

This is to align with the plan of RFC [here](https://github.com/redbrick/RFCs/blob/master/docs/RedbrickDoc2.md)

If you have any questions drop me a line but I believe there is the place for both these documents.

**Comment by butlerx** [comment]
api blueprints arent markdown they are MSON, moving them to markdown loses some of the details that are in the blueprint once rendered/parsed.

**Comment by theycallmemac** [comment]
I don't think any inferred that the blueprints were already markdown. This PR doesn't seem to be removing the blueprint itself, he's just adding a markdown version too for standardisation purposes as outlined above.

**Comment by gruunday** [comment]
Reading the file I see nothing. This is purely so you can find info in a central location and then go to the repo to find out more information.

**Comment by theycallmemac** [comment]
@gruunday I think this is more than okay to merge. Can you request a review ? Then I can merge this

**Pull request merged**
